//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.10 at 09:44:08 AM EDT 
//


package com.hertz;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Location" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="systemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="locationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="locationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="rentalCarBrand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="isHertzBrand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="dialect" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="oagCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="preferredOagCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="operationOwnershipType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="trainLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="airport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="airportName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="hoursOfOperation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="hoursOfOperation2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="hoursOfOperation3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="locationHoursTable">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="serviceDays">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="serviceDaysID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="dayOfTheWeek" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="isOpen24Hours" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="isClosedOnthisDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="serviceHours">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="serviceHoursID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="openTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="closeTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="addresses">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="addressType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="isoStateProvinceCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="stateProvinceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="postalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="lon" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="phones">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="phoneType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="countryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="areaCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="localNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="notesData">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="noteType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="noteName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="noteDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "location"
})
@XmlRootElement(name = "LocationForSearch")
public class LocationForSearch {

    @XmlElement(name = "Location", required = true)
    protected List<LocationForSearch.Location> location;

    /**
     * Gets the value of the location property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the location property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationForSearch.Location }
     * 
     * 
     */
    public List<LocationForSearch.Location> getLocation() {
        if (location == null) {
            location = new ArrayList<LocationForSearch.Location>();
        }
        return this.location;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="systemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="locationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="locationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="rentalCarBrand" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="isHertzBrand" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="dialect" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="oagCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="preferredOagCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="operationOwnershipType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="trainLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="airport" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="airportName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="hoursOfOperation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="hoursOfOperation2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="hoursOfOperation3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="locationHoursTable">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="serviceDays">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="serviceDaysID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="dayOfTheWeek" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="isOpen24Hours" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="isClosedOnthisDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="serviceHours">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="serviceHoursID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="openTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="closeTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="addresses">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="addressType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="isoStateProvinceCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="stateProvinceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="postalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="lon" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="phones">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="phoneType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="countryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="areaCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="localNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="notesData">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="noteType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="noteName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="noteDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "systemId",
        "locationId",
        "locationName",
        "rentalCarBrand",
        "isHertzBrand",
        "dialect",
        "oagCode",
        "preferredOagCode",
        "operationOwnershipType",
        "trainLocation",
        "airport",
        "airportName",
        "hoursOfOperation",
        "hoursOfOperation2",
        "hoursOfOperation3",
        "locationHoursTable",
        "addresses",
        "phones",
        "notesData"
    })
    public static class Location {

        @XmlElement(required = true)
        protected String systemId;
        @XmlElement(required = true)
        protected String locationId;
        @XmlElement(required = true)
        protected String locationName;
        @XmlElement(required = true)
        protected String rentalCarBrand;
        @XmlElement(required = true)
        protected String isHertzBrand;
        @XmlElement(required = true)
        protected String dialect;
        @XmlElement(required = true)
        protected String oagCode;
        @XmlElement(required = true)
        protected String preferredOagCode;
        @XmlElement(required = true)
        protected String operationOwnershipType;
        @XmlElement(required = true)
        protected String trainLocation;
        @XmlElement(required = true)
        protected String airport;
        @XmlElement(required = true)
        protected String airportName;
        @XmlElement(required = true)
        protected String hoursOfOperation;
        @XmlElement(required = true)
        protected String hoursOfOperation2;
        @XmlElement(required = true)
        protected String hoursOfOperation3;
        @XmlElement(required = true)
        protected LocationForSearch.Location.LocationHoursTable locationHoursTable;
        @XmlElement(required = true)
        protected LocationForSearch.Location.Addresses addresses;
        @XmlElement(required = true)
        protected LocationForSearch.Location.Phones phones;
        @XmlElement(required = true)
        protected LocationForSearch.Location.NotesData notesData;

        /**
         * Gets the value of the systemId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSystemId() {
            return systemId;
        }

        /**
         * Sets the value of the systemId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSystemId(String value) {
            this.systemId = value;
        }

        /**
         * Gets the value of the locationId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocationId() {
            return locationId;
        }

        /**
         * Sets the value of the locationId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocationId(String value) {
            this.locationId = value;
        }

        /**
         * Gets the value of the locationName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocationName() {
            return locationName;
        }

        /**
         * Sets the value of the locationName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocationName(String value) {
            this.locationName = value;
        }

        /**
         * Gets the value of the rentalCarBrand property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRentalCarBrand() {
            return rentalCarBrand;
        }

        /**
         * Sets the value of the rentalCarBrand property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRentalCarBrand(String value) {
            this.rentalCarBrand = value;
        }

        /**
         * Gets the value of the isHertzBrand property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsHertzBrand() {
            return isHertzBrand;
        }

        /**
         * Sets the value of the isHertzBrand property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsHertzBrand(String value) {
            this.isHertzBrand = value;
        }

        /**
         * Gets the value of the dialect property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDialect() {
            return dialect;
        }

        /**
         * Sets the value of the dialect property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDialect(String value) {
            this.dialect = value;
        }

        /**
         * Gets the value of the oagCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOagCode() {
            return oagCode;
        }

        /**
         * Sets the value of the oagCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOagCode(String value) {
            this.oagCode = value;
        }

        /**
         * Gets the value of the preferredOagCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPreferredOagCode() {
            return preferredOagCode;
        }

        /**
         * Sets the value of the preferredOagCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPreferredOagCode(String value) {
            this.preferredOagCode = value;
        }

        /**
         * Gets the value of the operationOwnershipType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOperationOwnershipType() {
            return operationOwnershipType;
        }

        /**
         * Sets the value of the operationOwnershipType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOperationOwnershipType(String value) {
            this.operationOwnershipType = value;
        }

        /**
         * Gets the value of the trainLocation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrainLocation() {
            return trainLocation;
        }

        /**
         * Sets the value of the trainLocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrainLocation(String value) {
            this.trainLocation = value;
        }

        /**
         * Gets the value of the airport property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAirport() {
            return airport;
        }

        /**
         * Sets the value of the airport property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAirport(String value) {
            this.airport = value;
        }

        /**
         * Gets the value of the airportName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAirportName() {
            return airportName;
        }

        /**
         * Sets the value of the airportName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAirportName(String value) {
            this.airportName = value;
        }

        /**
         * Gets the value of the hoursOfOperation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHoursOfOperation() {
            return hoursOfOperation;
        }

        /**
         * Sets the value of the hoursOfOperation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHoursOfOperation(String value) {
            this.hoursOfOperation = value;
        }

        /**
         * Gets the value of the hoursOfOperation2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHoursOfOperation2() {
            return hoursOfOperation2;
        }

        /**
         * Sets the value of the hoursOfOperation2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHoursOfOperation2(String value) {
            this.hoursOfOperation2 = value;
        }

        /**
         * Gets the value of the hoursOfOperation3 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHoursOfOperation3() {
            return hoursOfOperation3;
        }

        /**
         * Sets the value of the hoursOfOperation3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHoursOfOperation3(String value) {
            this.hoursOfOperation3 = value;
        }

        /**
         * Gets the value of the locationHoursTable property.
         * 
         * @return
         *     possible object is
         *     {@link LocationForSearch.Location.LocationHoursTable }
         *     
         */
        public LocationForSearch.Location.LocationHoursTable getLocationHoursTable() {
            return locationHoursTable;
        }

        /**
         * Sets the value of the locationHoursTable property.
         * 
         * @param value
         *     allowed object is
         *     {@link LocationForSearch.Location.LocationHoursTable }
         *     
         */
        public void setLocationHoursTable(LocationForSearch.Location.LocationHoursTable value) {
            this.locationHoursTable = value;
        }

        /**
         * Gets the value of the addresses property.
         * 
         * @return
         *     possible object is
         *     {@link LocationForSearch.Location.Addresses }
         *     
         */
        public LocationForSearch.Location.Addresses getAddresses() {
            return addresses;
        }

        /**
         * Sets the value of the addresses property.
         * 
         * @param value
         *     allowed object is
         *     {@link LocationForSearch.Location.Addresses }
         *     
         */
        public void setAddresses(LocationForSearch.Location.Addresses value) {
            this.addresses = value;
        }

        /**
         * Gets the value of the phones property.
         * 
         * @return
         *     possible object is
         *     {@link LocationForSearch.Location.Phones }
         *     
         */
        public LocationForSearch.Location.Phones getPhones() {
            return phones;
        }

        /**
         * Sets the value of the phones property.
         * 
         * @param value
         *     allowed object is
         *     {@link LocationForSearch.Location.Phones }
         *     
         */
        public void setPhones(LocationForSearch.Location.Phones value) {
            this.phones = value;
        }

        /**
         * Gets the value of the notesData property.
         * 
         * @return
         *     possible object is
         *     {@link LocationForSearch.Location.NotesData }
         *     
         */
        public LocationForSearch.Location.NotesData getNotesData() {
            return notesData;
        }

        /**
         * Sets the value of the notesData property.
         * 
         * @param value
         *     allowed object is
         *     {@link LocationForSearch.Location.NotesData }
         *     
         */
        public void setNotesData(LocationForSearch.Location.NotesData value) {
            this.notesData = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="addressType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="isoStateProvinceCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="stateProvinceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="postalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="lon" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "addressType",
            "address1",
            "city",
            "isoStateProvinceCode",
            "stateProvinceName",
            "postalCode",
            "lat",
            "lon"
        })
        public static class Addresses {

            @XmlElement(required = true)
            protected String addressType;
            @XmlElement(required = true)
            protected String address1;
            @XmlElement(required = true)
            protected String city;
            @XmlElement(required = true)
            protected String isoStateProvinceCode;
            @XmlElement(required = true)
            protected String stateProvinceName;
            @XmlElement(required = true)
            protected String postalCode;
            @XmlElement(required = true)
            protected String lat;
            @XmlElement(required = true)
            protected String lon;

            /**
             * Gets the value of the addressType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddressType() {
                return addressType;
            }

            /**
             * Sets the value of the addressType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddressType(String value) {
                this.addressType = value;
            }

            /**
             * Gets the value of the address1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddress1() {
                return address1;
            }

            /**
             * Sets the value of the address1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddress1(String value) {
                this.address1 = value;
            }

            /**
             * Gets the value of the city property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCity() {
                return city;
            }

            /**
             * Sets the value of the city property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCity(String value) {
                this.city = value;
            }

            /**
             * Gets the value of the isoStateProvinceCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsoStateProvinceCode() {
                return isoStateProvinceCode;
            }

            /**
             * Sets the value of the isoStateProvinceCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsoStateProvinceCode(String value) {
                this.isoStateProvinceCode = value;
            }

            /**
             * Gets the value of the stateProvinceName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStateProvinceName() {
                return stateProvinceName;
            }

            /**
             * Sets the value of the stateProvinceName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStateProvinceName(String value) {
                this.stateProvinceName = value;
            }

            /**
             * Gets the value of the postalCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPostalCode() {
                return postalCode;
            }

            /**
             * Sets the value of the postalCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPostalCode(String value) {
                this.postalCode = value;
            }

            /**
             * Gets the value of the lat property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLat() {
                return lat;
            }

            /**
             * Sets the value of the lat property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLat(String value) {
                this.lat = value;
            }

            /**
             * Gets the value of the lon property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLon() {
                return lon;
            }

            /**
             * Sets the value of the lon property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLon(String value) {
                this.lon = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="serviceDays">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="serviceDaysID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="dayOfTheWeek" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="isOpen24Hours" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="isClosedOnthisDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="serviceHours">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="serviceHoursID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="openTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="closeTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "serviceDays"
        })
        public static class LocationHoursTable {

            @XmlElement(required = true)
            protected LocationForSearch.Location.LocationHoursTable.ServiceDays serviceDays;

            /**
             * Gets the value of the serviceDays property.
             * 
             * @return
             *     possible object is
             *     {@link LocationForSearch.Location.LocationHoursTable.ServiceDays }
             *     
             */
            public LocationForSearch.Location.LocationHoursTable.ServiceDays getServiceDays() {
                return serviceDays;
            }

            /**
             * Sets the value of the serviceDays property.
             * 
             * @param value
             *     allowed object is
             *     {@link LocationForSearch.Location.LocationHoursTable.ServiceDays }
             *     
             */
            public void setServiceDays(LocationForSearch.Location.LocationHoursTable.ServiceDays value) {
                this.serviceDays = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="serviceDaysID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="dayOfTheWeek" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="isOpen24Hours" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="isClosedOnthisDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="serviceHours">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="serviceHoursID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="openTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="closeTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "serviceDaysID",
                "dayOfTheWeek",
                "isOpen24Hours",
                "isClosedOnthisDay",
                "effectiveDate",
                "serviceHours"
            })
            public static class ServiceDays {

                @XmlElement(required = true)
                protected String serviceDaysID;
                @XmlElement(required = true)
                protected String dayOfTheWeek;
                @XmlElement(required = true)
                protected String isOpen24Hours;
                @XmlElement(required = true)
                protected String isClosedOnthisDay;
                @XmlElement(required = true)
                protected String effectiveDate;
                @XmlElement(required = true)
                protected LocationForSearch.Location.LocationHoursTable.ServiceDays.ServiceHours serviceHours;

                /**
                 * Gets the value of the serviceDaysID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getServiceDaysID() {
                    return serviceDaysID;
                }

                /**
                 * Sets the value of the serviceDaysID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setServiceDaysID(String value) {
                    this.serviceDaysID = value;
                }

                /**
                 * Gets the value of the dayOfTheWeek property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDayOfTheWeek() {
                    return dayOfTheWeek;
                }

                /**
                 * Sets the value of the dayOfTheWeek property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDayOfTheWeek(String value) {
                    this.dayOfTheWeek = value;
                }

                /**
                 * Gets the value of the isOpen24Hours property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIsOpen24Hours() {
                    return isOpen24Hours;
                }

                /**
                 * Sets the value of the isOpen24Hours property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIsOpen24Hours(String value) {
                    this.isOpen24Hours = value;
                }

                /**
                 * Gets the value of the isClosedOnthisDay property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIsClosedOnthisDay() {
                    return isClosedOnthisDay;
                }

                /**
                 * Sets the value of the isClosedOnthisDay property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIsClosedOnthisDay(String value) {
                    this.isClosedOnthisDay = value;
                }

                /**
                 * Gets the value of the effectiveDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEffectiveDate() {
                    return effectiveDate;
                }

                /**
                 * Sets the value of the effectiveDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEffectiveDate(String value) {
                    this.effectiveDate = value;
                }

                /**
                 * Gets the value of the serviceHours property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link LocationForSearch.Location.LocationHoursTable.ServiceDays.ServiceHours }
                 *     
                 */
                public LocationForSearch.Location.LocationHoursTable.ServiceDays.ServiceHours getServiceHours() {
                    return serviceHours;
                }

                /**
                 * Sets the value of the serviceHours property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link LocationForSearch.Location.LocationHoursTable.ServiceDays.ServiceHours }
                 *     
                 */
                public void setServiceHours(LocationForSearch.Location.LocationHoursTable.ServiceDays.ServiceHours value) {
                    this.serviceHours = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="serviceHoursID" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="openTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="closeTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "serviceHoursID",
                    "openTime",
                    "closeTime"
                })
                public static class ServiceHours {

                    @XmlElement(required = true)
                    protected String serviceHoursID;
                    @XmlElement(required = true)
                    protected String openTime;
                    @XmlElement(required = true)
                    protected String closeTime;

                    /**
                     * Gets the value of the serviceHoursID property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getServiceHoursID() {
                        return serviceHoursID;
                    }

                    /**
                     * Sets the value of the serviceHoursID property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setServiceHoursID(String value) {
                        this.serviceHoursID = value;
                    }

                    /**
                     * Gets the value of the openTime property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getOpenTime() {
                        return openTime;
                    }

                    /**
                     * Sets the value of the openTime property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setOpenTime(String value) {
                        this.openTime = value;
                    }

                    /**
                     * Gets the value of the closeTime property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCloseTime() {
                        return closeTime;
                    }

                    /**
                     * Sets the value of the closeTime property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCloseTime(String value) {
                        this.closeTime = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="noteType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="noteName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="noteDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "noteType",
            "noteName",
            "noteDescription"
        })
        public static class NotesData {

            @XmlElement(required = true)
            protected String noteType;
            @XmlElement(required = true)
            protected String noteName;
            @XmlElement(required = true)
            protected String noteDescription;

            /**
             * Gets the value of the noteType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNoteType() {
                return noteType;
            }

            /**
             * Sets the value of the noteType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNoteType(String value) {
                this.noteType = value;
            }

            /**
             * Gets the value of the noteName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNoteName() {
                return noteName;
            }

            /**
             * Sets the value of the noteName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNoteName(String value) {
                this.noteName = value;
            }

            /**
             * Gets the value of the noteDescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNoteDescription() {
                return noteDescription;
            }

            /**
             * Sets the value of the noteDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNoteDescription(String value) {
                this.noteDescription = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="phoneType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="countryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="areaCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="localNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "phoneType",
            "countryCode",
            "areaCode",
            "localNumber"
        })
        public static class Phones {

            @XmlElement(required = true)
            protected String phoneType;
            @XmlElement(required = true)
            protected String countryCode;
            @XmlElement(required = true)
            protected String areaCode;
            @XmlElement(required = true)
            protected String localNumber;

            /**
             * Gets the value of the phoneType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPhoneType() {
                return phoneType;
            }

            /**
             * Sets the value of the phoneType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPhoneType(String value) {
                this.phoneType = value;
            }

            /**
             * Gets the value of the countryCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountryCode() {
                return countryCode;
            }

            /**
             * Sets the value of the countryCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountryCode(String value) {
                this.countryCode = value;
            }

            /**
             * Gets the value of the areaCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAreaCode() {
                return areaCode;
            }

            /**
             * Sets the value of the areaCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAreaCode(String value) {
                this.areaCode = value;
            }

            /**
             * Gets the value of the localNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocalNumber() {
                return localNumber;
            }

            /**
             * Sets the value of the localNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocalNumber(String value) {
                this.localNumber = value;
            }

        }

    }

}
